### ISSUE TITLE
Fixing the notes from submission 1 Riemann Solver

### ISSUE THREAD

**Issue by RivinHD** [RivinHD/Tsunami-Simulation#24]
- [x]  I am usually not a fan of having generated data under version control (here sphinx build).
But this is debatable.

***

- [x] Integration of movies and the Doxygen in Sphinx is nice.
The font of the doxygen part seems to get smaller on every level; can this be fixed?

***

- [x] The math sections require proper citations, e.g., "The f-wave solver approximately solves the following Initial Value Problem (IVP) for the shallow water equations over time".

***

- [x] In the project report It would be helpful to describe what you and why.

***

- [x] ``t_real l_h = 0.5f * ( i_hL + i_hR );`` t_real(0.5) would be better for the constant.
In this case the result is the same since 0.5 can be stored exactly.

***

- [x] ``t_real denominator = i_eigenvalue2 - i_eigenvalue1;`` similar to your pre-computed square root, one would precompute the division and then simply multiply.
Note: This was not required in this assignment, we have a dedicated optimization one later.

***

- [x] The documentation of o_deltaFlux is inaccurate.
You are not computing the difference of the quantities but the difference of the flux function after inserting the quantities.
  ```cpp
       * @param o_deltaFlux output: difference of left and right quantities
       */
       static void computeDeltaFlux(t_real i_hL,
                               t_real i_hR,
                               t_real i_uL,
                               t_real i_uR,
                               t_real o_deltaFlux[2]);
  ```

***

- [x]  ``#include <iostream>`` in FWave.cpp: Probably a leftover from printf debugging.
Do not include headers which are not used.

***

- [x] The indentation is off.
  ```cpp
  void tsunami_lab::solvers::FWave::computeEigenvalues(t_real   i_hL,
                                                 t_real   i_hR,
                                                 t_real   i_uL,
                                                 t_real   i_uR,
                                                 t_real & o_eigenvalue1,
                                                 t_real & o_eigenvalue2){
  ```

***

- [x] "Building the Simulation"
You can't *build* a simulation.
You can build a numerical solver and run a simulation.

***

- [x] "E.g. the build executable can be run with the following command:"
build is an uncommon name for an executable

***

- [x] Does not match your cmake build.
  ```bash
  
  ####################################
  ### Tsunami Lab                  ###
  ###                              ###
  ### https://scalable.uni-jena.de ###
  ####################################
  invalid number of arguments, usage:
    ./build/tsunami_lab N_CELLS_X
  ```

**Comment by Integer-Ctrl** [comment]
All done.
